### ISSUE TITLE
0.0.34 패키지에 바이러스(트로이목마)가 포함되어 있습니다.

### ISSUE THREAD

**Issue by WildAtticLab** [sniper-internet/Sniper-desktop-release#3]
Symantec Anti-virus에 의하면, 0.0.34 버전 패키지는
**Heur.AdvML.B** 에 감염되어 있습니다.
https://www.symantec.com/security-center/writeup/2016-051811-2400-99

전 MacOS 버전을 사용했는데, 관련 내용보니 윈도우 계열에 영향을 미치는 바이러스네요.
설치 시 관련 바이러스가 함께 감염됩니다.

패키지 배포를 중지해주시고, 버전 업데이트 해서 재배포 부탁드립니다.

**Comment by researcherGeekLab** [comment]
WinDivert때문에 일부 Anti-Virus에서 탐지하는 듯합니다. 
Malicious가 아닌 PUA(Potentially Unwanted Application)로 진단하는 것 봐서는 문제 없을 듯합니다.
말씀하신 Symantec도 휴리스틱 진단으로 진단하는 것봐서 오진일 가능성이 큰 것같습니다.
해당 이슈는 Symantec에 제가 오진으로 제보하겠습니다.

**Comment by WildAtticLab** [comment]
빠른 답변 감사드립니다.
늘 응원하겠습니다.

**Comment by kicKORhIT-16384-needSYDney** [comment]
Just Commenting.
Currently I'm using Norton Security, and it does not detect it as PUA.
Seems like issue is solved.
